# Generated by Django 4.1.2 on 2022-10-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$kFTDeKO8BiJgI2J1SvL3Wx$NIgHYSDI0NmirK14792e6flzg3QfUCtBAe2RymWSXPo=', max_length=128),
        ),
        migrations.AlterModelTable(
            name='horse',
            table='horse',
        ),
    ]
