# Generated by Django 4.1.2 on 2022-10-21 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horseimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$jThoncF6qrgiJZVQYZryNB$iXS2t4T9pYnHuoLONO5C2mne/sevLh+DocjRl4f/SwA=', max_length=128),
        ),
    ]
