# Generated by Django 4.1.2 on 2022-10-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_alter_horse_password_alter_horse_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$ufq5W6EWqzcaXNAYYpeHrb$YX85Q78F8swjMdqL7A0YwEfit9LvO7AF4pBvSgo7Ugw=', max_length=128),
        ),
    ]
