# Generated by Django 4.1.2 on 2022-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_alter_horseimage_user_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$UcM7FkKtCLztKPOhkmSLmr$AZWW+fGuTIatdtBZwccDqEar+FymJiwBQl3FWbY2sWA=', max_length=128),
        ),
    ]
