# Generated by Django 4.1.2 on 2022-10-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_alter_horseimage_user_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='examined_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Msj84QRbOmrj1UEgybIet6$I7jdIj1Y+xwZWYNyBu2Yo/3GKWzQrqClZLn62FqOIbo=', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
