# Generated by Django 4.1.2 on 2022-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$dFE05nJaxjM6BykEnBI8bS$42pA4asnIW/6wSu5MMR7L5jgobxNDaO9xyBG+OvCEqs=', max_length=128),
        ),
    ]
