# Generated by Django 4.1.2 on 2022-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_alter_user_birth_day_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$4BKBEVaz2mt8LtiBFvEVzR$ZrT8SJgDl1XHAmS+p1oKJ7fde+Jps9F0XoXO45mvYJQ=', max_length=128),
        ),
    ]
