# Generated by Django 4.1.2 on 2022-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$7kSoakIp1a3hidgRLV5SfI$+rk+AIyVZKyKLx/mW8mQkRnjJINZOjVv6TAX0Xsh9Go=', max_length=128),
        ),
    ]
