# Generated by Django 4.1.2 on 2022-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$9XQJdDIlSOFSnLkBfQAd5l$UGn2DojTtwSP3i5yBZ/rDd3DmKwnEjIG0aN/9KOK40s=', max_length=128),
        ),
    ]
