# Generated by Django 4.1.2 on 2022-10-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$bgBTouca62rIDZaBhE8oYq$xidfdAnaCk6Rs/kO7Ef2X+olQEBcp7hqviEyvRjA68Y=', max_length=128),
        ),
    ]
