# Generated by Django 4.1.2 on 2022-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$PuVlo0DBeK1iNbx7FmdfFe$lkkdtz3wAWI85aTsX5uEOyWKyp+C4CtMlUkcuppBSak=', max_length=128),
        ),
    ]
