# Generated by Django 4.1.2 on 2022-11-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$lubvEm2fZm3capTvkexTPZ$Co/JQbadj3/w1nKuFvdum86LYAS00ytA/C5hBRPTyqs=', max_length=128),
        ),
    ]
