# Generated by Django 4.1.2 on 2022-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$oQbcIMwwHrWSXFLh6yvTtO$1/XWjxYoIooeFvkvPmRw54hGdwTAZYIcToSTBaYSTbU=', max_length=128),
        ),
    ]
