# Generated by Django 4.1.2 on 2022-11-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$sKUthU7Nk0wnN6dQdgD7KY$NvyV1Ep+7V6p1dYbwUm6uL9afL6knhF9P2ce7fIfCpw=', max_length=128),
        ),
    ]
