# Generated by Django 4.1.2 on 2022-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$QxyfsNVvWBnHaisuf7x6OO$p/xceMNjzo+3YNWKzbWdOODVbZatce/x2UxO41t6Y28=', max_length=128),
        ),
    ]
