# Generated by Django 4.1.2 on 2022-11-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$2azaKnv3Jp60h0BQs1s7gi$Et0CK88YC2fVlfAABTNmCCcbEZPEyU8wCekjiTuf8xM=', max_length=128),
        ),
    ]
