# Generated by Django 4.1.2 on 2022-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$VJg535PQfzdnCzdznGi9Ey$g3BtaHM+KtC9EtudUbe1yshnlu+1sGWYuElUdM9cmkI=', max_length=128),
        ),
    ]
