# Generated by Django 4.1.2 on 2022-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$o9vMHYtIr5Ccl24OWGOLvm$1KuxKOrK5sxSlvd+G2orsPpYukcffpTUAfT/IHDJ7fk=', max_length=128),
        ),
    ]
