# Generated by Django 4.1.2 on 2022-11-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0010_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Y7rFR18B7lFBg0OztFhSFx$5URgvvTfUSrM6KxAU9iSBCPE+0qiT19SPWUe/VFPlSg=', max_length=128),
        ),
    ]
