# Generated by Django 4.1.2 on 2022-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$q79hEKsfL7nWtXjjW7aXhw$pMv+pL14mJFnAosEcJ8iBbkLYIfZwSS/Rc/eaEDgFY4=', max_length=128),
        ),
    ]
