# Generated by Django 4.1.2 on 2022-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$txc6xmS4RkAIgTMMsVbkrz$et+BoQW0yVJtPiS5haca/AFCdr6xMxwhYKOszmPl43Q=', max_length=128),
        ),
    ]
