# Generated by Django 4.1.2 on 2022-11-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$M7LOUiEHE69Um1b17sr7YC$EbxgWe4SU/HZKlRNyoaci0pO/v5yMeXbkr5PvyYPVbM=', max_length=128),
        ),
    ]
