# Generated by Django 4.1.2 on 2022-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$bObPHrdSb0cyl8bYi57tjH$HI1N8qqmwUmdWg2IiAtFkF8zqjsnYuO6B7PXYZnLFsw=', max_length=128),
        ),
    ]
