# Generated by Django 4.1.2 on 2022-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0013_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$sHE3a4l9Iabi59kUgBM5F8$6MYDqwjcNynZ8c6dTLYC8NAWpciTq6agNCKT2W6YEzo=', max_length=128),
        ),
    ]
