# Generated by Django 4.1.2 on 2022-11-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$uz0ic8ojvvIi4yXl0PoNIJ$s4ow/mGPN1DEGU+g562KoI4Ow+QDOLVImp+4b3j36Ts=', max_length=128),
        ),
    ]
