# Generated by Django 4.1.2 on 2022-10-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$yHyxmSg0fni4mqcQyecZde$WL/+vm3kxgZiyJCDB2kI+79g8DWYtHw25+rt0pa/iWc=', max_length=128),
        ),
    ]
