# Generated by Django 4.1.2 on 2022-10-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$pFuoeUEycmyz0T81gjlgKX$xdyb5dKFkwu0LEEz0ppYbAE1bYEom+YpUKYDe6VzVyo=', max_length=128),
        ),
    ]
