# Generated by Django 4.1.2 on 2022-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$cXupVC1XqS0PTbRQCeJaKN$Ll2uDij7I1pC960QmnWAw9AaJtSjRtwL1ZeWjZtboW8=', max_length=128),
        ),
    ]
