# Generated by Django 4.1.2 on 2022-11-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$b4dPwNu3lJhz5gbuBQan1F$6tvUV+TDbGqEF/b5L4qhyZIGmCor91K6R86ocNvP1Ew=', max_length=128),
        ),
    ]
