# Generated by Django 4.1.2 on 2022-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$DkP0ab9LQgZB14nImM8RLA$asUY6l/HkwPLQn11jhpc84rZATanpU6h+RuxCzptJdM=', max_length=128),
        ),
    ]
