# Generated by Django 4.1.2 on 2022-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$NUAeceGEEAeOe5QEYdKIL9$wlZ0fv1l+cJfVdKPIHq17fdrslKZy+XHQgV1EPosrR4=', max_length=128),
        ),
    ]
