# Generated by Django 4.1.2 on 2022-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$1Vr5bLUDhyws8bwyAMp4lF$vtLjmm2YH4KYjjxgKn7A+ANeBnAPlYO9ciCxogVUdK8=', max_length=128),
        ),
    ]
