# Generated by Django 4.1.2 on 2022-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0019_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$XpsdruMG2SXQtLNbNRplX1$usuwZKDmWT4C8C98kGaMINV57p92ha/10JDjMkq4K04=', max_length=128),
        ),
    ]
