# Generated by Django 4.1.2 on 2022-11-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$Uj13ODDBOgw7zgt6ml0FH2$+YwkWbKvQfDXhnIZR/UrFkPyKAsE4aXB19WoUOnxDGo=', max_length=128),
        ),
    ]
