# Generated by Django 4.1.2 on 2022-11-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0021_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$8dV8KpNclTYUntR3Z7x1hw$il4ERNSqn9xjqlYrXhbu1tTDarwYtGwl7UiY2q5IU/4=', max_length=128),
        ),
    ]
