# Generated by Django 4.1.2 on 2022-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$OPGE9IkePAAJyyfHJdQWRd$DD4JojVgDkbAOknnoKQe9x31AI7tVtH29SKTysPL/NM=', max_length=128),
        ),
    ]
