# Generated by Django 4.1.2 on 2022-11-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$GrCzChqKKXTYnNcxtBPXXW$XimZud3+NNXLoLda8XLBGsjZ5j9dWjKjhJkngSGofOY=', max_length=128),
        ),
    ]
