# Generated by Django 4.1.2 on 2022-11-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$wIOlUgF52HydZYNcixY0sG$BhBq9zDEYi4LabjS1ST7fVPzDeoFbcR+NNMB6nO27zY=', max_length=128),
        ),
    ]
