# Generated by Django 4.1.2 on 2022-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$gc1VbLkRblSbeGyGgimtc0$eu5/LS60iqR8wJp98Ard+PBZzTfe9PyxnSOXf5Eqz40=', max_length=128),
        ),
    ]
