# Generated by Django 4.1.2 on 2022-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$JLoKctN7G44KuNGeTlKpLY$tyoFkAwk+Sod3r0kAWCkgH237xKT7LPrZhR4aS1rsvc=', max_length=128),
        ),
    ]
