# Generated by Django 4.1.2 on 2022-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$o7UUKSTcAb6Tbw9EDO72OC$9CiuABadEMClSWoHHuT3MyrVYAXbzcKnK+AgZrcSuDM=', max_length=128),
        ),
    ]
