# Generated by Django 4.1.2 on 2022-11-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0030_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$pZpQefvFpEEcJQlKuO7yoI$INF0enWvcRblBxnnZFSI22wwXO5JNSwSpdb7Fs457c0=', max_length=128),
        ),
    ]
