# Generated by Django 4.1.2 on 2022-11-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$ynMyNR8rVJcRnR8CbdyPZt$BD+ele9RsWZ3Qqs/hKjNssFya+53jzvEbIdc+no1lJI=', max_length=128),
        ),
    ]
