# Generated by Django 4.1.2 on 2022-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0032_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$m8FCMHLKGlZBVr3UZXGbZT$lvCcu6HTiCGc96dnHQDFM+mMgyETgd+w//laOnZKafI=', max_length=128),
        ),
    ]
