# Generated by Django 4.1.2 on 2022-10-16 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/dop_images", verbose_name="Фотография"
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография",
                "verbose_name_plural": "Доп_Фотографии",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Фото пользователя",
                    ),
                ),
                (
                    "user_bg",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Background",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="О себе"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="eMail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "workPhone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Рабочий Номер телефона",
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Instagram"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Facebook"
                    ),
                ),
                (
                    "twitter",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Twitter"
                    ),
                ),
                (
                    "telegram",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Telegram"
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на LinkedIn"
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на YouTube"
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на WhatsApp"
                    ),
                ),
                (
                    "behance",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на Behance"
                    ),
                ),
                (
                    "other_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Другая ссылка"
                    ),
                ),
                ("unique_id", models.UUIDField(blank=True, null=True)),
                ("key", models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.image",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
    ]
