version: '3.9'

services:
  postgres_db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: lc_menu
      POSTGRES_USER: hikki
      POSTGRES_PASSWORD: adi
    container_name: postgres_db

  web:
    build: .
    volumes:
      - ./:/app/
      - ./static:/app/static/
      - ./media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    container_name: web
    env_file:
      - ../.env/
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
#      image: linuxserver/swag
      image: nginx:latest
      restart: always
      depends_on:
          - web
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/nginx.conf:/config/nginx/site-confs/default
          - ./media:/usr/media/
#          - lets:/config/keys/
          - ./static:/usr/static/

volumes:
  postgres_data:
#  lets:

